using System;

namespace DAL.Models
{
    public class NewRole : BaseEntity
    {
        public Guid? Id { get; set; }
        public string UserRoleName { get; set; }
        public string Description { get; set; }
        public bool? TeamMemberManagement { get; set; }
        public bool? ViewUsers { get; set; }
        public bool? ManageUsers { get; set; }
        public bool? CreateTeams { get; set; }
        public bool? InviteTeamMembers { get; set; }
        public bool? CompanyProfile { get; set; }
        public bool? ViewComapnyProfile { get; set; }
        public bool? EditCompanyProfile { get; set; }
        public bool? RoleManagment { get; set; }
        public bool? ViewRoles { get; set; }
        public bool? CreateNewRoles { get; set; }
        public bool? Customer360 { get; set; }
        public bool? ViewAccounts { get; set; }
        public bool? CreateAccounts { get; set; }
        public bool? EditAccounts { get; set; }
        public bool? DeleteAccounts { get; set; }
        public bool? ViewContacts { get; set; }
        public bool? CreateContacts { get; set; }
        public bool? EditContacts { get; set; }
        public bool? DeleteContacts { get; set; }
        public bool? Appointments { get; set; }
        public bool? CreateCategoryAndSubcategory { get; set; }
        public bool? EditCategoryAndSubcategory { get; set; }
        public bool? ViewCategoryAndSubcategory { get; set; }
        public bool? DeleteCategoryAndSubcategory { get; set; }
        public bool? AddDignosticQuestionAndAnswer { get; set; }
        public bool? DeleteDignosticQuestionAndAnswer { get; set; }
        public bool? UpdateAvailabilityCalender { get; set; }
        public bool? CreateAppointment { get; set; }
        public bool? EditExistingAppointment { get; set; }
        public bool? CreateNewQuote { get; set; }
        public bool? EditExistingQuote { get; set; }
        public bool? ViewQuote { get; set; }
        public bool? DeleteQuote { get; set; }
        public bool? WorkOrderManagment { get; set; }
        public bool? CreateNewWorkOrder { get; set; }
        public bool? EditExistingWorkOrder { get; set; }
        public bool? DeleteWorkOrder { get; set; }
        public bool? DispatcherAndScheduler { get; set; }
        public bool? EstimatesAndQuotes { get; set; }
        public bool? View { get; set; }
        public bool? Modify { get; set; }
        public bool? InvoiceAndPayments { get; set; }
        public bool? CreateNewInvoice { get; set; }
        public bool? EditExistingInvoice { get; set; }
        public bool? ViewInvoice { get; set; }
        public bool? DeleteInvoice { get; set; }
        public bool? CreateCreditNote { get; set; }
        public bool? EditCreditNote { get; set; }
        public bool? ViewCreditNote { get; set; }
        public bool? CreateNewPaymentReciept { get; set; }
        public bool? EditExistingPaymentReciept { get; set; }
        public bool? DeletePaymentReciept { get; set; }
        public bool? ViewPaymentReciept { get; set; }
        public bool? ClientContracts { get; set; }
        public bool? ViewContracts { get; set; }
        public bool? ModifyExistingContracts { get; set; }
        public bool? DeleteContracts { get; set; }
        public bool? AssetManagment { get; set; }
        public bool? CreateNewAsset { get; set; }
        public bool? EditAsset { get; set; }
        public bool? DeleteAsset { get; set; }
        public bool? InventoryManagment { get; set; }
        public bool? CreateNewWarehouse { get; set; }
        public bool? EditExistingWarehouse { get; set; }
        public bool? DeleteWarehouse { get; set; }
        public bool? CreateNewItems { get; set; }
        public bool? EditItems { get; set; }
        public bool? DeleteItems { get; set; }
        public bool? CreateTransferOrder { get; set; }
        public bool? ApproveTransferOrder { get; set; }
        public bool? ItemAdjustment { get; set; }
        public bool? CreateSalesOrder { get; set; }
        public bool? ModifySalesOrder { get; set; }
        public bool? CreatePickList { get; set; }
        public bool? ApprovePickList { get; set; }
        public bool? ViewPickList { get; set; }
        public bool? ModifyPickList { get; set; }
        public bool? CreatePackList { get; set; }
        public bool? ApprovePackList { get; set; }
        public bool? ViewPackList { get; set; }
        public bool? ModifyPackList { get; set; }
        public bool? CreateShipList { get; set; }
        public bool? ApproveShipList { get; set; }
        public bool? ViewShipList { get; set; }
        public bool? ModifyShipList { get; set; }
        public bool? SupplierManagment { get; set; }
        public bool? CreateNewVendor { get; set; }
        public bool? CreatePurchaseOrder { get; set; }
        public bool? EditPurchaseOrder { get; set; }
        public bool? DeletePurchaseOrder { get; set; }
        public bool? ViewPurchaseOrder { get; set; }
        public bool? CreateNewBill { get; set; }
        public bool? DeleteBill { get; set; }
        public bool? EditBill { get; set; }
        public bool? KnowladgeManagement { get; set; }
        public bool? CreateFolders { get; set; }
        public bool? DeleteFolders { get; set; }
        public bool? UploadDocument { get; set; }
        public bool? DeleteDocuments { get; set; }
        public bool? AskToEtaprise { get; set; }
        public bool? Dashboards { get; set; }
        public bool? ServicePerformance { get; set; }
        public bool? BusinessPerformance { get; set; }
        public bool? DispacherDashboard { get; set; }
        public bool? FinancialDashboard { get; set; }
        public bool? PlanningAndForcasting { get; set; }
        public bool? MasterConfigrations { get; set; }
        public bool? CreateJobDefination { get; set; }
        public bool? UpdateJobDefination { get; set; }
        public bool? ViewJobDefination { get; set; }
        public bool? DeleteJobDefination { get; set; }
        public bool? ViewTimesheet { get; set; }
        public bool? EditTimesheet { get; set; }
        public bool? ApproveLeave { get; set; }
        public bool? ViewLeaveRequest { get; set; }
        public bool? ViewPayrollInformation { get; set; }
        public bool? EditPayrollInformation { get; set; }
        public bool? CreateNewShift { get; set; }
        public bool? UpdateShift { get; set; }
        public bool? DeleteShift { get; set; }
        public bool? QuickBooksSync { get; set; }
        public bool? Xero { get; set; }
        public bool? FieldNation { get; set; }
        public bool? HomeAdvisor { get; set; }
        public bool? Yelp { get; set; }
        public bool? Google { get; set; }
        public bool? Angi { get; set; }
        public bool? PhyxterHomeServices { get; set; }
        public bool? HomeStars { get; set; }
        public bool? Thumbtack { get; set; }
        public bool? Porch { get; set; }
        public bool? Houzz { get; set; }
    }
}
